default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: makersbnb_dev

test:
  <<: *default
  database: makersbnb_test

production:
  <<: *default
  database: makersbnb
